import { useState } from "react"
import { Play } from "lucide-react"
import { Link } from "react-router-dom"

import type { MediaDetail } from "@/api/client"
import { Button } from "@/components/ui/button"
import { AddPage } from "@/features/media/add-page"
import { BackLink, DetailError, DetailHero, DetailLoading, InfoGrid, PeopleRow, Section } from "@/features/media/detail-shared"
import { useMediaDetail } from "@/features/media/use-media-detail"
import { formatDate, formatRuntime } from "@/features/media/format"
import { formatPersonalRating } from "@/features/media/rating-scale"
import { useRatingScale } from "@/features/media/rating-scale-context"
import { LibraryPage } from "@/features/media/library-page"
import { Modal } from "@/features/media/modal"

export function MoviesPage({backlog=false}:{backlog?:boolean}){return <LibraryPage domain="movies" title="Movies" backlog={backlog} />}
export function AddMoviePage(){return <AddPage domain="movies" title="Movies" />}
export function MovieDetailPage(){const{detail,setDetail,loading,error,retry}=useMediaDetail("movies");const[trailer,setTrailer]=useState(false);if(loading)return <DetailLoading/>;if(error||!detail)return <DetailError message={error??"Movie not found."} retry={retry}/>;const changed=(value:MediaDetail)=>setDetail(value);return <div className="space-y-6"><BackLink domain="movies" label="Movies"/><DetailHero domain="movies" detail={detail} changed={changed} subtitle={[detail.year,formatRuntime(detail.runtimeMinutes),detail.director,detail.genres.slice(0,3).join(" · ")].filter(Boolean).join(" · ")} />{detail.trailerKey&&<Button type="button" variant="outline" onClick={()=>setTrailer(true)}><Play/>Play trailer</Button>}<Section title="Overview"><p className="max-w-4xl text-sm leading-7 text-muted-foreground">{detail.overview||"No overview is available."}</p></Section><Section title="Movie information"><InfoGrid items={[["Release date",formatDate(detail.releaseDate)],["Runtime",formatRuntime(detail.runtimeMinutes)],["Director",detail.director],["Genres",detail.genres.join(", ")],["Production companies",detail.productionCompanies?.join(", ")]]}/></Section>{!!detail.cast?.length&&<Section title="Cast"><PeopleRow people={detail.cast}/></Section>}{!!detail.crew?.length&&<Section title="Key crew"><PeopleRow people={detail.crew}/></Section>}{detail.collectionName&&<Section title={detail.collectionName}><Collection detail={detail}/></Section>}<Section title="External links"><div className="flex flex-wrap gap-2">{detail.homepage&&<Button asChild variant="outline" size="sm"><a href={detail.homepage} target="_blank" rel="noreferrer">Official site</a></Button>}{detail.imdbId&&<Button asChild variant="outline" size="sm"><a href={`https://www.imdb.com/title/${detail.imdbId}/`} target="_blank" rel="noreferrer">IMDb</a></Button>}<Button asChild variant="outline" size="sm"><a href={`https://www.themoviedb.org/movie/${detail.providerId}`} target="_blank" rel="noreferrer">TMDB</a></Button></div></Section>{trailer&&detail.trailerKey&&<Modal title={`${detail.title} trailer`} close={()=>setTrailer(false)} wide><div className="aspect-video overflow-hidden rounded-lg bg-black"><iframe title={`${detail.title} trailer`} src={`https://www.youtube-nocookie.com/embed/${encodeURIComponent(detail.trailerKey)}`} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen className="size-full"/></div></Modal>}</div>}
function Collection({detail}:{detail:MediaDetail}){const scale=useRatingScale();return <div className="flex gap-4 overflow-x-auto pb-2">{detail.collection?.map((item)=><article key={item.providerId} className="w-32 shrink-0"><div className="aspect-[2/3] overflow-hidden rounded-md bg-muted">{item.posterUrl&&<img src={item.posterUrl} alt="" loading="lazy" className="size-full object-cover"/>}</div><p className="mt-2 line-clamp-2 text-sm font-medium">{item.title}</p>{item.localId?<Link to={`/movies/${item.localId}`} className="text-xs text-muted-foreground underline">{item.localStatus}{item.localRating!==undefined?` · ${formatPersonalRating(item.localRating,scale)}`:""}</Link>:<Link to={`/movies/add?q=${encodeURIComponent(item.title)}`} className="text-xs text-muted-foreground underline">Not in Library</Link>}</article>)}</div>}
