// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAuthentication = `-- name: ActivateAuthentication :execrows
UPDATE authentication_state
SET activated = true,
    activated_at = now(),
    active_revision = $1,
    active_issuer_url = $2,
    active_client_id = $3,
    active_public_url = $4,
    updated_at = now()
WHERE singleton = true
  AND activated = false
  AND configuration_revision = $1
  AND validated_revision = $1
`

type ActivateAuthenticationParams struct {
	ActiveRevision  pgtype.Int8 `json:"active_revision"`
	ActiveIssuerUrl pgtype.Text `json:"active_issuer_url"`
	ActiveClientID  pgtype.Text `json:"active_client_id"`
	ActivePublicUrl pgtype.Text `json:"active_public_url"`
}

func (q *Queries) ActivateAuthentication(ctx context.Context, arg ActivateAuthenticationParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateAuthentication,
		arg.ActiveRevision,
		arg.ActiveIssuerUrl,
		arg.ActiveClientID,
		arg.ActivePublicUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const anyAdminExists = `-- name: AnyAdminExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE is_admin = true)
`

func (q *Queries) AnyAdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyAdminExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const applyActiveAuthenticationConfiguration = `-- name: ApplyActiveAuthenticationConfiguration :execrows
UPDATE authentication_state
SET active_revision = $1,
    active_issuer_url = $2,
    active_client_id = $3,
    active_public_url = $4,
    updated_at = now()
WHERE singleton = true
  AND activated = true
  AND configuration_revision = $1
  AND validated_revision = $1
`

type ApplyActiveAuthenticationConfigurationParams struct {
	ActiveRevision  pgtype.Int8 `json:"active_revision"`
	ActiveIssuerUrl pgtype.Text `json:"active_issuer_url"`
	ActiveClientID  pgtype.Text `json:"active_client_id"`
	ActivePublicUrl pgtype.Text `json:"active_public_url"`
}

func (q *Queries) ApplyActiveAuthenticationConfiguration(ctx context.Context, arg ApplyActiveAuthenticationConfigurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyActiveAuthenticationConfiguration,
		arg.ActiveRevision,
		arg.ActiveIssuerUrl,
		arg.ActiveClientID,
		arg.ActivePublicUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOIDCLoginFlow = `-- name: ConsumeOIDCLoginFlow :one
DELETE FROM oidc_login_flows
WHERE state_hash = $1
RETURNING algorithm_version, nonce, ciphertext, expires_at
`

type ConsumeOIDCLoginFlowRow struct {
	AlgorithmVersion int16              `json:"algorithm_version"`
	Nonce            []byte             `json:"nonce"`
	Ciphertext       []byte             `json:"ciphertext"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ConsumeOIDCLoginFlow(ctx context.Context, stateHash []byte) (ConsumeOIDCLoginFlowRow, error) {
	row := q.db.QueryRow(ctx, consumeOIDCLoginFlow, stateHash)
	var i ConsumeOIDCLoginFlowRow
	err := row.Scan(
		&i.AlgorithmVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.ExpiresAt,
	)
	return i, err
}

const createOIDCUser = `-- name: CreateOIDCUser :one
INSERT INTO users (oidc_issuer, oidc_subject, display_name, email, is_admin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, oidc_issuer, oidc_subject, display_name, email, is_admin, created_at, updated_at
`

type CreateOIDCUserParams struct {
	OidcIssuer  pgtype.Text `json:"oidc_issuer"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
	IsAdmin     bool        `json:"is_admin"`
}

type CreateOIDCUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	OidcIssuer  pgtype.Text        `json:"oidc_issuer"`
	OidcSubject pgtype.Text        `json:"oidc_subject"`
	DisplayName pgtype.Text        `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) (CreateOIDCUserRow, error) {
	row := q.db.QueryRow(ctx, createOIDCUser,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.DisplayName,
		arg.Email,
		arg.IsAdmin,
	)
	var i CreateOIDCUserRow
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.DisplayName,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredOIDCLoginFlows = `-- name: DeleteExpiredOIDCLoginFlows :execrows
WITH expired AS (
    SELECT state_hash
    FROM oidc_login_flows
    WHERE expires_at <= now()
    ORDER BY expires_at
    LIMIT $1
)
DELETE FROM oidc_login_flows
WHERE state_hash IN (SELECT state_hash FROM expired)
`

func (q *Queries) DeleteExpiredOIDCLoginFlows(ctx context.Context, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCLoginFlows, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
WITH expired AS (
    SELECT id
    FROM sessions
    WHERE expires_at <= now()
       OR (revoked_at IS NOT NULL AND revoked_at <= now() - interval '1 day')
    ORDER BY expires_at
    LIMIT $1
)
DELETE FROM sessions
WHERE id IN (SELECT id FROM expired)
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT value
FROM app_settings
WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getAuthenticationState = `-- name: GetAuthenticationState :one
SELECT configuration_revision,
       validated_revision,
       validated_at,
       activated,
       activated_at,
       active_revision,
       active_issuer_url,
       active_client_id,
       active_public_url
FROM authentication_state
WHERE singleton = true
`

type GetAuthenticationStateRow struct {
	ConfigurationRevision int64              `json:"configuration_revision"`
	ValidatedRevision     pgtype.Int8        `json:"validated_revision"`
	ValidatedAt           pgtype.Timestamptz `json:"validated_at"`
	Activated             bool               `json:"activated"`
	ActivatedAt           pgtype.Timestamptz `json:"activated_at"`
	ActiveRevision        pgtype.Int8        `json:"active_revision"`
	ActiveIssuerUrl       pgtype.Text        `json:"active_issuer_url"`
	ActiveClientID        pgtype.Text        `json:"active_client_id"`
	ActivePublicUrl       pgtype.Text        `json:"active_public_url"`
}

func (q *Queries) GetAuthenticationState(ctx context.Context) (GetAuthenticationStateRow, error) {
	row := q.db.QueryRow(ctx, getAuthenticationState)
	var i GetAuthenticationStateRow
	err := row.Scan(
		&i.ConfigurationRevision,
		&i.ValidatedRevision,
		&i.ValidatedAt,
		&i.Activated,
		&i.ActivatedAt,
		&i.ActiveRevision,
		&i.ActiveIssuerUrl,
		&i.ActiveClientID,
		&i.ActivePublicUrl,
	)
	return i, err
}

const getAuthenticationStateForUpdate = `-- name: GetAuthenticationStateForUpdate :one
SELECT configuration_revision,
       validated_revision,
       activated,
       active_revision,
       active_issuer_url,
       active_client_id,
       active_public_url
FROM authentication_state
WHERE singleton = true
FOR UPDATE
`

type GetAuthenticationStateForUpdateRow struct {
	ConfigurationRevision int64       `json:"configuration_revision"`
	ValidatedRevision     pgtype.Int8 `json:"validated_revision"`
	Activated             bool        `json:"activated"`
	ActiveRevision        pgtype.Int8 `json:"active_revision"`
	ActiveIssuerUrl       pgtype.Text `json:"active_issuer_url"`
	ActiveClientID        pgtype.Text `json:"active_client_id"`
	ActivePublicUrl       pgtype.Text `json:"active_public_url"`
}

func (q *Queries) GetAuthenticationStateForUpdate(ctx context.Context) (GetAuthenticationStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthenticationStateForUpdate)
	var i GetAuthenticationStateForUpdateRow
	err := row.Scan(
		&i.ConfigurationRevision,
		&i.ValidatedRevision,
		&i.Activated,
		&i.ActiveRevision,
		&i.ActiveIssuerUrl,
		&i.ActiveClientID,
		&i.ActivePublicUrl,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id,
       s.user_id,
       s.expires_at,
       s.revoked_at,
       u.oidc_issuer,
       u.oidc_subject,
       u.display_name,
       u.email,
       u.is_admin,
       a.active_public_url
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN authentication_state a ON a.singleton = true
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	OidcIssuer      pgtype.Text        `json:"oidc_issuer"`
	OidcSubject     pgtype.Text        `json:"oidc_subject"`
	DisplayName     pgtype.Text        `json:"display_name"`
	Email           pgtype.Text        `json:"email"`
	IsAdmin         bool               `json:"is_admin"`
	ActivePublicUrl pgtype.Text        `json:"active_public_url"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.DisplayName,
		&i.Email,
		&i.IsAdmin,
		&i.ActivePublicUrl,
	)
	return i, err
}

const getUserByOIDCIdentity = `-- name: GetUserByOIDCIdentity :one
SELECT id, oidc_issuer, oidc_subject, display_name, email, is_admin, created_at, updated_at
FROM users
WHERE oidc_issuer = $1 AND oidc_subject = $2
`

type GetUserByOIDCIdentityParams struct {
	OidcIssuer  pgtype.Text `json:"oidc_issuer"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
}

type GetUserByOIDCIdentityRow struct {
	ID          pgtype.UUID        `json:"id"`
	OidcIssuer  pgtype.Text        `json:"oidc_issuer"`
	OidcSubject pgtype.Text        `json:"oidc_subject"`
	DisplayName pgtype.Text        `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByOIDCIdentity(ctx context.Context, arg GetUserByOIDCIdentityParams) (GetUserByOIDCIdentityRow, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCIdentity, arg.OidcIssuer, arg.OidcSubject)
	var i GetUserByOIDCIdentityRow
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.DisplayName,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAuthenticationConfigurationRevision = `-- name: IncrementAuthenticationConfigurationRevision :one
UPDATE authentication_state
SET configuration_revision = configuration_revision + 1,
    validated_revision = NULL,
    validated_at = NULL,
    updated_at = now()
WHERE singleton = true
RETURNING configuration_revision
`

func (q *Queries) IncrementAuthenticationConfigurationRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, incrementAuthenticationConfigurationRevision)
	var configuration_revision int64
	err := row.Scan(&configuration_revision)
	return configuration_revision, err
}

const insertOIDCLoginFlow = `-- name: InsertOIDCLoginFlow :exec
INSERT INTO oidc_login_flows (
    state_hash, algorithm_version, nonce, ciphertext, expires_at
) VALUES ($1, $2, $3, $4, $5)
`

type InsertOIDCLoginFlowParams struct {
	StateHash        []byte             `json:"state_hash"`
	AlgorithmVersion int16              `json:"algorithm_version"`
	Nonce            []byte             `json:"nonce"`
	Ciphertext       []byte             `json:"ciphertext"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertOIDCLoginFlow(ctx context.Context, arg InsertOIDCLoginFlowParams) error {
	_, err := q.db.Exec(ctx, insertOIDCLoginFlow,
		arg.StateHash,
		arg.AlgorithmVersion,
		arg.Nonce,
		arg.Ciphertext,
		arg.ExpiresAt,
	)
	return err
}

const markAuthenticationConfigurationValidated = `-- name: MarkAuthenticationConfigurationValidated :execrows
UPDATE authentication_state
SET validated_revision = $1,
    validated_at = now(),
    updated_at = now()
WHERE singleton = true
  AND configuration_revision = $1
`

func (q *Queries) MarkAuthenticationConfigurationValidated(ctx context.Context, validatedRevision pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, markAuthenticationConfigurationValidated, validatedRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteUserToAdmin = `-- name: PromoteUserToAdmin :one
UPDATE users
SET is_admin = true,
    updated_at = now()
WHERE id = $1 AND is_admin = false
RETURNING id, oidc_issuer, oidc_subject, display_name, email, is_admin, created_at, updated_at
`

type PromoteUserToAdminRow struct {
	ID          pgtype.UUID        `json:"id"`
	OidcIssuer  pgtype.Text        `json:"oidc_issuer"`
	OidcSubject pgtype.Text        `json:"oidc_subject"`
	DisplayName pgtype.Text        `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PromoteUserToAdmin(ctx context.Context, id pgtype.UUID) (PromoteUserToAdminRow, error) {
	row := q.db.QueryRow(ctx, promoteUserToAdmin, id)
	var i PromoteUserToAdminRow
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.DisplayName,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionByID = `-- name: RevokeSessionByID :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now()),
    updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now()),
    updated_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOIDCUser = `-- name: UpdateOIDCUser :one
UPDATE users
SET display_name = $2,
    email = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, oidc_issuer, oidc_subject, display_name, email, is_admin, created_at, updated_at
`

type UpdateOIDCUserParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Email       pgtype.Text `json:"email"`
}

type UpdateOIDCUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	OidcIssuer  pgtype.Text        `json:"oidc_issuer"`
	OidcSubject pgtype.Text        `json:"oidc_subject"`
	DisplayName pgtype.Text        `json:"display_name"`
	Email       pgtype.Text        `json:"email"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOIDCUser(ctx context.Context, arg UpdateOIDCUserParams) (UpdateOIDCUserRow, error) {
	row := q.db.QueryRow(ctx, updateOIDCUser, arg.ID, arg.DisplayName, arg.Email)
	var i UpdateOIDCUserRow
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.DisplayName,
		&i.Email,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
