// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"
)

const deleteIntegrationTestStatus = `-- name: DeleteIntegrationTestStatus :exec
DELETE FROM integration_test_status
WHERE provider = $1
`

func (q *Queries) DeleteIntegrationTestStatus(ctx context.Context, provider string) error {
	_, err := q.db.Exec(ctx, deleteIntegrationTestStatus, provider)
	return err
}

const getIntegrationTestStatus = `-- name: GetIntegrationTestStatus :one
SELECT provider, status, message, tested_at, updated_at
FROM integration_test_status
WHERE provider = $1
`

func (q *Queries) GetIntegrationTestStatus(ctx context.Context, provider string) (IntegrationTestStatus, error) {
	row := q.db.QueryRow(ctx, getIntegrationTestStatus, provider)
	var i IntegrationTestStatus
	err := row.Scan(
		&i.Provider,
		&i.Status,
		&i.Message,
		&i.TestedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationTestStatuses = `-- name: ListIntegrationTestStatuses :many
SELECT provider, status, message, tested_at, updated_at
FROM integration_test_status
ORDER BY provider
`

func (q *Queries) ListIntegrationTestStatuses(ctx context.Context) ([]IntegrationTestStatus, error) {
	rows, err := q.db.Query(ctx, listIntegrationTestStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationTestStatus{}
	for rows.Next() {
		var i IntegrationTestStatus
		if err := rows.Scan(
			&i.Provider,
			&i.Status,
			&i.Message,
			&i.TestedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegrationTestStatus = `-- name: UpsertIntegrationTestStatus :one
INSERT INTO integration_test_status (provider, status, message, tested_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (provider) DO UPDATE SET
    status = EXCLUDED.status,
    message = EXCLUDED.message,
    tested_at = now(),
    updated_at = now()
RETURNING provider, status, message, tested_at, updated_at
`

type UpsertIntegrationTestStatusParams struct {
	Provider string `json:"provider"`
	Status   string `json:"status"`
	Message  string `json:"message"`
}

func (q *Queries) UpsertIntegrationTestStatus(ctx context.Context, arg UpsertIntegrationTestStatusParams) (IntegrationTestStatus, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationTestStatus, arg.Provider, arg.Status, arg.Message)
	var i IntegrationTestStatus
	err := row.Scan(
		&i.Provider,
		&i.Status,
		&i.Message,
		&i.TestedAt,
		&i.UpdatedAt,
	)
	return i, err
}
