// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuthenticationState struct {
	Singleton             bool               `json:"singleton"`
	ConfigurationRevision int64              `json:"configuration_revision"`
	ValidatedRevision     pgtype.Int8        `json:"validated_revision"`
	ValidatedAt           pgtype.Timestamptz `json:"validated_at"`
	Activated             bool               `json:"activated"`
	ActivatedAt           pgtype.Timestamptz `json:"activated_at"`
	ActiveRevision        pgtype.Int8        `json:"active_revision"`
	ActiveIssuerUrl       pgtype.Text        `json:"active_issuer_url"`
	ActiveClientID        pgtype.Text        `json:"active_client_id"`
	ActivePublicUrl       pgtype.Text        `json:"active_public_url"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type EncryptionKeyState struct {
	Singleton      bool               `json:"singleton"`
	KeyFingerprint []byte             `json:"key_fingerprint"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Entity struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OidcLoginFlow struct {
	StateHash        []byte             `json:"state_hash"`
	AlgorithmVersion int16              `json:"algorithm_version"`
	Nonce            []byte             `json:"nonce"`
	Ciphertext       []byte             `json:"ciphertext"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type SecretSetting struct {
	Key              string             `json:"key"`
	AlgorithmVersion int16              `json:"algorithm_version"`
	Nonce            []byte             `json:"nonce"`
	Ciphertext       []byte             `json:"ciphertext"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SetupState struct {
	Singleton   bool               `json:"singleton"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SystemMetadatum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	ExternalSubject pgtype.Text        `json:"external_subject"`
	DisplayName     pgtype.Text        `json:"display_name"`
	Email           pgtype.Text        `json:"email"`
	IsAdmin         bool               `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OidcIssuer      pgtype.Text        `json:"oidc_issuer"`
	OidcSubject     pgtype.Text        `json:"oidc_subject"`
}
