// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EncryptionKeyState struct {
	Singleton      bool               `json:"singleton"`
	KeyFingerprint []byte             `json:"key_fingerprint"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Entity struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SecretSetting struct {
	Key              string             `json:"key"`
	AlgorithmVersion int16              `json:"algorithm_version"`
	Nonce            []byte             `json:"nonce"`
	Ciphertext       []byte             `json:"ciphertext"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SetupState struct {
	Singleton   bool               `json:"singleton"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SystemMetadatum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	ExternalSubject pgtype.Text        `json:"external_subject"`
	DisplayName     pgtype.Text        `json:"display_name"`
	Email           pgtype.Text        `json:"email"`
	IsAdmin         bool               `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
