// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
)

const countSecretSettings = `-- name: CountSecretSettings :one
SELECT count(*)
FROM secret_settings
`

func (q *Queries) CountSecretSettings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSecretSettings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSecretSetting = `-- name: DeleteSecretSetting :execrows
DELETE FROM secret_settings
WHERE key = $1
`

func (q *Queries) DeleteSecretSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecretSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEncryptionKeyFingerprint = `-- name: GetEncryptionKeyFingerprint :one
SELECT key_fingerprint
FROM encryption_key_state
WHERE singleton = true
`

func (q *Queries) GetEncryptionKeyFingerprint(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEncryptionKeyFingerprint)
	var key_fingerprint []byte
	err := row.Scan(&key_fingerprint)
	return key_fingerprint, err
}

const getEncryptionKeyFingerprintForUpdate = `-- name: GetEncryptionKeyFingerprintForUpdate :one
SELECT key_fingerprint
FROM encryption_key_state
WHERE singleton = true
FOR UPDATE
`

func (q *Queries) GetEncryptionKeyFingerprintForUpdate(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEncryptionKeyFingerprintForUpdate)
	var key_fingerprint []byte
	err := row.Scan(&key_fingerprint)
	return key_fingerprint, err
}

const getSecretSetting = `-- name: GetSecretSetting :one
SELECT key, algorithm_version, nonce, ciphertext
FROM secret_settings
WHERE key = $1
`

type GetSecretSettingRow struct {
	Key              string `json:"key"`
	AlgorithmVersion int16  `json:"algorithm_version"`
	Nonce            []byte `json:"nonce"`
	Ciphertext       []byte `json:"ciphertext"`
}

func (q *Queries) GetSecretSetting(ctx context.Context, key string) (GetSecretSettingRow, error) {
	row := q.db.QueryRow(ctx, getSecretSetting, key)
	var i GetSecretSettingRow
	err := row.Scan(
		&i.Key,
		&i.AlgorithmVersion,
		&i.Nonce,
		&i.Ciphertext,
	)
	return i, err
}

const listSecretSettings = `-- name: ListSecretSettings :many
SELECT key, algorithm_version, nonce, ciphertext
FROM secret_settings
ORDER BY key
`

type ListSecretSettingsRow struct {
	Key              string `json:"key"`
	AlgorithmVersion int16  `json:"algorithm_version"`
	Nonce            []byte `json:"nonce"`
	Ciphertext       []byte `json:"ciphertext"`
}

func (q *Queries) ListSecretSettings(ctx context.Context) ([]ListSecretSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSecretSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretSettingsRow{}
	for rows.Next() {
		var i ListSecretSettingsRow
		if err := rows.Scan(
			&i.Key,
			&i.AlgorithmVersion,
			&i.Nonce,
			&i.Ciphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerEncryptionKeyFingerprint = `-- name: RegisterEncryptionKeyFingerprint :exec
INSERT INTO encryption_key_state (singleton, key_fingerprint)
VALUES (true, $1)
ON CONFLICT (singleton) DO NOTHING
`

func (q *Queries) RegisterEncryptionKeyFingerprint(ctx context.Context, keyFingerprint []byte) error {
	_, err := q.db.Exec(ctx, registerEncryptionKeyFingerprint, keyFingerprint)
	return err
}

const upsertSecretSetting = `-- name: UpsertSecretSetting :exec
INSERT INTO secret_settings (key, algorithm_version, nonce, ciphertext)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET algorithm_version = EXCLUDED.algorithm_version,
    nonce = EXCLUDED.nonce,
    ciphertext = EXCLUDED.ciphertext,
    updated_at = now()
`

type UpsertSecretSettingParams struct {
	Key              string `json:"key"`
	AlgorithmVersion int16  `json:"algorithm_version"`
	Nonce            []byte `json:"nonce"`
	Ciphertext       []byte `json:"ciphertext"`
}

func (q *Queries) UpsertSecretSetting(ctx context.Context, arg UpsertSecretSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSecretSetting,
		arg.Key,
		arg.AlgorithmVersion,
		arg.Nonce,
		arg.Ciphertext,
	)
	return err
}
