// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value
FROM app_settings
ORDER BY key
`

type ListAppSettingsRow struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) ListAppSettings(ctx context.Context) ([]ListAppSettingsRow, error) {
	rows, err := q.db.Query(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppSettingsRow{}
	for rows.Next() {
		var i ListAppSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type UpsertAppSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.Exec(ctx, upsertAppSetting, arg.Key, arg.Value)
	return err
}
