// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package db

import (
	"context"
)

const completeSetup = `-- name: CompleteSetup :execrows
UPDATE setup_state
SET completed = true, completed_at = now(), updated_at = now()
WHERE singleton = true AND completed = false
`

func (q *Queries) CompleteSetup(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, completeSetup)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSetupComplete = `-- name: GetSetupComplete :one
SELECT completed
FROM setup_state
WHERE singleton = true
`

func (q *Queries) GetSetupComplete(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getSetupComplete)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}
